[project]
name = "farstpro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shaker-Al-Muzaini", email = "sshakiralmazini@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "greenlet>=3.5.5",
    "pydantic>=2.13.5",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]

[project.scripts]
farstpro = "farstpro:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
